### ISSUE TITLE
Status 401 for unauthenticated users

### ISSUE THREAD

**Issue by Pacific112** [ulisesbocchio/spring-boot-security-saml#10]
I'm trying to override default behaviour of SAML and return Status 401 after unathorized request, so frontend application will be able to interpret this in some way (probably redirect to /saml/login endpoint). 

Earlier i was doing this by overriding SAMLEntryPoint, but using your configurer (wnich is awesome) i can't provide custom implementation of this class.

Could you provide possibility to configure this? Or am i missing something and this is possible?

**Comment by ulisesbocchio** [comment]
I will definitely look into it! Will keep you posted

**Comment by Pacific112** [comment]
I've created Pull Request that adds possibility to provide custom SamlEntryPoint implementation. Please, take a look: https://github.com/ulisesbocchio/spring-boot-security-saml/pull/11

**Comment by ulisesbocchio** [comment]
Thanks @Pacific112 , I merged your changes. I'll create a release soon too.

**Comment by ulisesbocchio** [comment]
1.7 has been release with your contribution, thanks!
