### ISSUE TITLE
How to configure storage factory using serviceProviderSecurityBuilder

### ISSUE THREAD

**Issue by samtheprogrammer** [ulisesbocchio/spring-boot-security-saml#14]
Hi i need to set the property storageFactory as follows is there a way to do this with serviceProviderConfigurerAdapter

<bean id="contextProvider" class="org.springframework.security.saml.context.SAMLContextProviderImpl">
  <property name="storageFactory">
    <bean class="org.springframework.security.saml.storage.EmptyStorageFactory"/>
  </property>
</bean>

**Comment by samtheprogrammer** [comment]
figured it out 

	and()
	.metadataGenerator()
				.includeDiscoveryExtension(true).and().samlContextProvider(contextProvider());


and context provider

public SAMLContextProviderImpl contextProvider(){
		
		SAMLContextProviderImpl contextProvider = new SAMLContextProviderImpl();
		contextProvider.setStorageFactory(emptyStorageFactory);
		return contextProvider;
	}

**Comment by ulisesbocchio** [comment]
Yup, that's it!

**Comment by ulisesbocchio** [comment]
You can also just provide a bean definition:

```java
    @Bean
    public SAMLContextProvider samlContextProvider() {
        SAMLContextProviderImpl contextProvider = new SAMLContextProviderImpl();
	contextProvider.setStorageFactory(emptyStorageFactory);
	return contextProvider;
    }
```

And the plugin will pick it up automatically without you having to specify it explicitly with the DSL
