### ISSUE TITLE
How to disable automatic metadata generator for preconfigured metadata

### ISSUE THREAD

**Issue by samtheprogrammer** [ulisesbocchio/spring-boot-security-saml#19]
http://docs.spring.io/spring-security-saml/docs/current/reference/html/configuration-metadata.html#configuration-metadata-sp-import

it says, if i need to use preconfigured metadata i will have to disable automatic metadata generator 
using this
<security:custom-filter before="FIRST" ref="metadataGeneratorFilter"/>

How do i achieve this if i am using you plugin and spring boot 

SAM

**Comment by ulisesbocchio** [comment]
I'm gonna have to dig into how you could do that in a streamlined way.

**Comment by samtheprogrammer** [comment]
thanks a lot

**Comment by ulisesbocchio** [comment]
I added support for static SP metadata in version 1.10, enjoy. [Here's](https://github.com/ulisesbocchio/spring-boot-security-saml-samples/tree/master/spring-boot-security-saml-demo-static-metadata) a sample app using static local metadata
