### ISSUE TITLE
UnsupportedOperationException on use of saml.sso.key-manager.key-passwords.<alias>

### ISSUE THREAD

**Issue by marcthornton** [ulisesbocchio/spring-boot-security-saml#2]
I spent some time digging into an UnsupportedOperationException in using the saml.sso.key-manager.keypasswords._alias_ property (application.properties or application.yml).  Originally, I thought it was the format of my _alias_ but eventually determined that even a simple alias password would fail ie

```
saml.sso.key-manager.default-key=samlclient
saml.sso.key-manager.key-passwords.samlclient=mypassword
```

There doesn't seem to be an issue with specifying the key passwords using the Java DSL approach but the same cannot be specified using the application.properties or application.yml.

I believe the issue is the use of the default value for KeyManagerProperties#keyPasswords, which is:
`    Map<String, String> keyPasswords = Collections.singletonMap("localhost", "");`

The result of Collections.singletonMap(..) cannot be modified, hence raises the UnsupportedOperationException.  The KeyManagerConfigurer used in the Java DSL approach avoids this issue by having its own local copy of the keyPasswords fields, where it can do a null check and instantiate a standard HashMap.

Attempting to build after setting KeyManagerProperties#keyPasswords field to default value ie
`    Map<String, String> keyPasswords;`
fails on initialization in test cases due to a check in:
`    KeyManagerProperties#validateDefaultKeyAndPasswords()`

I have yet to confirm whether skipping the tests will allow the code to work as expected, but there may be other regression impacts to making this seemingly minor change.

**Comment by ulisesbocchio** [comment]
Hi @marcthornton, thanks for the heads up. I totally get what you mean. I'll get that fixed for you as soon as possible.

**Comment by marcthornton** [comment]
I appreciate the quick feedback, @ulisesbocchio.

Overall, I must say that you've done some really nice work with this addition.  The default saml-security-saml configuration is pretty extensive & complex, even for someone who knows the nuts & bolts of SAML.  It gets even more complex when trying to integrate the default project with spring-boot (which I did with a mix of @ImportResource/XML and Spring Security Java DSL).. but your approach is definitely nice & clean, integrating very well!

**Comment by ulisesbocchio** [comment]
Thanks for the comments @marcthornton, the fix for the problem you were experiencing is out the door in version 1.1, please give it try whenever you have a chance (might take a while to show up in maven central).
Best,
Uli
