### ISSUE TITLE
Plans for integration with the Spring projects portfolio

### ISSUE THREAD

**Issue by javiboo** [ulisesbocchio/spring-boot-security-saml#20]
Hi @ulisesbocchio,

Congrats for your work! Do you thought about to integrate this project with the other projects from Spring Security?

Thanks!

**Comment by ulisesbocchio** [comment]
Hi @javiboo, thanks :) Which other Spring Security projects are you interested in integrating this plugin with?

**Comment by javiboo** [comment]
@ulisesbocchio sorry for not answering before. I meant that if you'll make a PR to integrate this project into Spring portfolio and go to be mantained by Pivotal.

**Comment by ulisesbocchio** [comment]
@javiboo, I see. That'd be great actually, I'm not sure it is up to their standards and how to get the ball rolling for something like that. Have you done anything like that?
