### ISSUE TITLE
Missing ServiceProviderConfigurer

### ISSUE THREAD

**Issue by proactif** [ulisesbocchio/spring-boot-security-saml#21]
Spring Boot 1.4.3
using spring-boot-security-saml 1.8
with just props config
and @EnableSAMLSSO on main class

I get :
Application startup failed
...
No qualifying bean of type 'java.util.List<com.github.ulisesbocchio.spring.boot.security.saml.configurer.ServiceProviderConfigurer>' available

What am I missing ?

**Comment by ulisesbocchio** [comment]
can you share you app config?

**Comment by ulisesbocchio** [comment]
fixed the issue, new version should be in maven central soon.
