### ISSUE TITLE
JWT and SAML 2.0

### ISSUE THREAD

**Issue by nixgadget** [ulisesbocchio/spring-boot-security-saml#22]
With this spring security extension can we mix with JWT authentication ?

**Comment by ulisesbocchio** [comment]
You can mix this spring security extension with whatever you want. Depending on how you're planning to mix in JWT you may have to use the [WebSecurityConfigurerAdapter](https://github.com/ulisesbocchio/spring-boot-security-saml#using-websecurityconfigureradapter) flavor to have full control of Spring Security.
