### ISSUE TITLE
The documentation points to incorrect property

### ISSUE THREAD

**Issue by ruoat** [ulisesbocchio/spring-boot-security-saml#23]
Hi,
Before the version 1.10 I had the following configuration:
`saml.sso.idps.metadata-location: classpath:/idp-foo-test.xml`

But after the [commit](https://github.com/ulisesbocchio/spring-boot-security-saml/commit/4ca15976e0dd67a056b1bc06e4068a2e2a023cb2)
things have been changed. I had to rename the property to
`saml.sso.idp.metadata-location: classpath:/idp-foo-test.xml`

The documentation still mentions the idps-section in the property. If the change in the naming is intentional the documentation should be updated.

**Comment by ulisesbocchio** [comment]
thanks @ruoat, I fixed the docs.
