### ISSUE TITLE
How to generate key pair(.der private key and .cert public key) ?

### ISSUE THREAD

**Issue by gustvn** [ulisesbocchio/spring-boot-security-saml#28]
In README.md, you doesn't write the way to generate key pair. That's important to config the key manager of service provider. I can't config my staging server without key pair of key manager

**Comment by ulisesbocchio** [comment]
sure buddy, I'll add that to te README. If you can't wait, here's how you could generate a self signed pair:
```bash
# KEY AND CERT
openssl genrsa -out localhost.key 2048
openssl req -new -x509 -key localhost.key -out localhost.pem -days 3650 -subj /CN=localhost
# PEM KEY to DER
openssl pkcs8 -topk8 -inform PEM -outform DER -in  localhost.key -out  localhost.key.der -nocrypt
```

**Comment by gangapatnam-suresh** [comment]
Dear ulisesbocchio,

I have used your example for one of my spring boot app ( zuul gateway ) and trying to enable SSO with keycloak IDP.

I have generated the self signed certificate key pairs(as mentioned above) for my spring-boot app and trying to authenticate with keycloak IDP. I have uploaded the localhost.pem/localhost.cert file for the client i have configured at Keycloak IDP.

when i try to authenticate with IDP from my spring-boot app, i get the this error 

13:56:21,236 WARN  [org.keycloak.events] (default task-44) type=LOGIN_ERROR, realmId=test, clientId=null, userId=null, ipAddress=127.0.0.1, error=invalid_token

Can you help me on this.?
