### ISSUE TITLE
@EnableSAMLSSO from a Configuration class

### ISSUE THREAD

**Issue by yihfenglow** [ulisesbocchio/spring-boot-security-saml#31]
Hi,

First of all, a big thank you for open sourcing this project. It has been incredibly helpful.

I was wondering if we are meant to use @EnableSAMLSSO annotation on an @Configuration class, rather than in the Spring Boot Application class?

The reason why I think this would be beneficial is that we can then use the Spring @Profile annotation to by-pass SAML and fall back to basic HTTP authentication in a local development environment. 

The README file seems to indicate that this is possible. However, when I move the @EnableSAMLSSO annotation from the Application class to a configuration, it always fails with:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is org.springframework.security.config.annotation.AlreadyBuiltException: This object has already been built`

**Comment by ulisesbocchio** [comment]
Interesting, I've never tried that, if you would've asked before telling me it doesn't work I would have bet it did. Let me dig on that...
 You can certainly try the `WebSecurityConfigurerAdapter` approach with the `SAMLConfigurerBean` bean that's [explained in the README](https://github.com/ulisesbocchio/spring-boot-security-saml#using-websecurityconfigureradapter). That version is meant to be used  with other security configurations, so you can certainly mix basic and SAML that way.

**Comment by ulisesbocchio** [comment]
I [this example](https://github.com/ulisesbocchio/spring-boot-security-saml-samples/blob/master/spring-boot-security-saml-demo-dsl/src/main/java/com/github/ulisesbocchio/demo/SpringBootSecuritySAMLDemoApplication.java), move the `@EnableSAMLSSO` annotation from next to `@SpringBootApplication` to next to the `@Configuration` annotation on `MyServiceProviderConfig` and everything works the same. Not sure how it didn't work but please feel free to reopen with a sample configuration that I can reproduce.

**Comment by yihfenglow** [comment]
Hi Ulises,

Thanks for the response.

I was actually using the WebSecurityConfigererAdapter, and attaching the @EnableSAMLSSO annotation on that class and that was what was throwing the error. I'm not sure if you would be able to reproduce this, it could just be down to some other dependency I have on my classpath that is interfering.

I tried it with ServiceProviderConfigurerAdapter and it seems to have worked. 

Thanks again!

**Comment by worldsayshi** [comment]
Heads up for anyone else looking for guidance: @ulisesbocchio's comment above is aimed at [this version](https://github.com/ulisesbocchio/spring-boot-security-saml-samples/blob/4cd25fb8f2ad7f17715ab48ced21b281b8a2c543/spring-boot-security-saml-demo-props/src/main/java/com/github/ulisesbocchio/demo/SpringBootSecuritySAMLDemoApplication.java) of the example.
