### ISSUE TITLE
Infinite loop with a custom SAMLUserDetailsService throwing UsernameNotFoundException

### ISSUE THREAD

**Issue by vincentditlevinz** [ulisesbocchio/spring-boot-security-saml#32]
A SAMLUserDetailsService , according to specs, may throw a UsernameNotFoundException. In such case, there is an infinite loop in ProviderManager.authenticate() beacause of the existence of a parent AuthenticationManager that attempt to exactly perform the same SAMLAuthenticationProvider.authenticate() call that still lead to a UsernameNotFoundException.

This is very similar to https://stackoverflow.com/questions/27956378/infinte-loop-when-bad-credentials-are-entered-in-spring-security-form-login

Add 
```
@Override
        protected void configure(final AuthenticationManagerBuilder auth) throws Exception {
            auth.parentAuthenticationManager(null);
        }	
```

in SAMLWebSecurityConfigurer solves the bug.

**Comment by ulisesbocchio** [comment]
@vincentditlevinz thanks! Will add that soon

**Comment by ulisesbocchio** [comment]
Alright, added and tested this, will be releasing soon, thanks!

**Comment by ulisesbocchio** [comment]
new version is up, should be available in maven central shortly, enjoy!
