### ISSUE TITLE
Unable to extend SAMLEntrypoint

### ISSUE THREAD

**Issue by brankoiliccc** [ulisesbocchio/spring-boot-security-saml#38]
Adding 

@Bean
public SAMLEntryPoint customSamlEndpoints(){
return new CustomSAMLEntrypoint();
}

will fail on Parameter 0 of method setContextProvider in org.springframework.security.saml.SAMLEntryPoint required a bean of type 'org.springframework.security.saml.context.SAMLContextProvider' that could not be found.

if i just add 

serviceProvider.metadataGenerator()
		               .entityId(spConfig.getEntityId())
		               .entityBaseURL(spConfig.getEntityBaseUrl())
                .and().sso()
                	  .samlEntryPoint(new CustomSAMLEntrypoint())

Will fail with 
Cannot register after unregistered Filter class org.springframework.security.saml.SAMLEntryPoint

Due to 
com.github.ulisesbocchio.spring.boot.security.saml.bean.SAMLConfigurerBean.addFilter(HttpSecurity, Class<? extends Filter>)  --- org.springframework.security.config.annotation.web.builders.FilterComparator.getOrder(Class<?>) which tries to locate filter by class name or super-class name.

**Comment by ulisesbocchio** [comment]
This is true, at the moment you need to stick to the `SAMLEntrypoint` class. I have a fix for this that I'll be releasing a few days. Thanks for reporting the issue!

**Comment by ulisesbocchio** [comment]
Enjoy! https://github.com/ulisesbocchio/spring-boot-security-saml/releases/tag/v1.13
