### ISSUE TITLE
sso binding property doesnt work

### ISSUE THREAD

**Issue by avinash92c** [ulisesbocchio/spring-boot-security-saml#4]
saml.sso.metadata-generator.bindings-sso=paos

adding this to application properties  wouldn't enable **paos** endpoint.
always keeps exposing default post,artifact endpoints.

**Comment by ulisesbocchio** [comment]
There are 2 properties in spring saml for PAOS: 
`saml.sso.metadata-generator.bindings-SSO=paos,artifact,post` will enable those bindings in the generated metadata. (The property needs to have this exact casing)
And
`saml.sso.saml-processor.paos=true` will enable PAOS bindings at the Processor level, which basically affects the /saml/SSO endpoint. This last property is enabled by default.
