### ISSUE TITLE
Possible bug with SSOProcessingUrl

### ISSUE THREAD

**Issue by MGZero** [ulisesbocchio/spring-boot-security-saml#40]
I was running into a pretty big wall with this over the last few days.  I finally resolved it last night, but my fix is kind of not great and there may be an underlying bug.  For background first, I'm using dsl as follows:

               `serviceProvider
                .metadataGenerator()
                .entityId("zfgc-sp")
                .entityBaseURL("http://localhost:8080/forum")
                .requestSigned(false)
                .metadataURL("/saml/metadata")
            .and()
                .sso()
                .defaultSuccessURL("/home")
                .defaultFailureURL("/failTest")
                .idpSelectionPageURL("/idpselection")
                //.ssoProcessingURL("/forum/SSO")
                
            .and()
                .logout()
                .defaultTargetURL("/")
            .and()
                .metadataManager()
                .refreshCheckInterval(0)
                .metadataTrustCheck(false)
                //.localMetadataLocation("classpath:/sp-metadata.xml")
            .and()
                .extendedMetadata()
               
                //.signingKey("test")
                //.encryptionKey("test")
                //.idpDiscoveryEnabled(true)
                
            .and()
                .keyManager()
                //.privateKeyDERLocation("classpath:/localhost.key.der")
                //.publicKeyPEMLocation("classpath:/localhost.cert");
            .and()
	            .samlContextProviderLb()
	            .scheme("http")
	            .contextPath("/")
	            .serverName("localhost")
	            .serverPort(8080)
	            .includeServerPortInRequestURL(true);`

I'm also running off of Tomcat 8.0 in Eclipse, with the web module configured as such:

![image](https://user-images.githubusercontent.com/1524901/32992220-18447b4c-cd16-11e7-8e60-642b4f4d13e3.png)

I grabbed the metadata from localhost:8080/forum/saml/metadata. The ACS url came out like this, as expected:

http://localhost:8080/forum/saml/SSO

I added this to my IDP (a simple saml php server) and fired everything up for a test.  Everything worked great until the assertion was posted to my service provider, which returned this error:

`SAML message intended destination endpoint 'http://localhost:8080/forum/saml/SSO' did not match the recipient endpoint 'http://localhost:8080/saml/SSO`

Unless there's something I'm doing wrong, it seems that the metadata generator is taking the entity base url into account, while the endpoint itself is *not.*  I was able to get it working by removing /forum from the equation entirely, including the Tomcat web module config.  This isn't ideal though as I also have the jamwiki module which will also need to be its own SP at some point.

**Comment by ulisesbocchio** [comment]
your config has:

```java
.and()
            .samlContextProviderLb()
            .scheme("http")
            .contextPath("/")
            .serverName("localhost")
            .serverPort(8080)
            .includeServerPortInRequestURL(true);
```
where you're defining the context path explicitly. Set that to `/forum` if you want to receive your SAMLResponse on that endpoint.

**Comment by MGZero** [comment]
that worked, thanks!
