### ISSUE TITLE
how to use SwitchUserFilter with SAML

### ISSUE THREAD

**Issue by longthanhtran** [ulisesbocchio/spring-boot-security-saml#43]
I am trying to get SwitchUserFilter with SAML but stuck with `java.lang.IllegalArgumentException: null source` when SwitchUserFilter calls SecurityContextHolder.getContext().getAuthentication()

>
>		// publish event
>		if (this.eventPublisher != null) {
>			this.eventPublisher.publishEvent(new AuthenticationSwitchUserEvent(
>					SecurityContextHolder.getContext().getAuthentication(), targetUser));
>		}

so I think I don't know how to prepare or use SecurityContextHolder with SAML. Can you please guide me to do that @ulisesbocchio ? Thanks

**Comment by longthanhtran** [comment]
I figure it out by myself, I miss use WebSecurity to ignore the path which leads to no context.

**Comment by ulisesbocchio** [comment]
Great!
