### ISSUE TITLE
Getting AccessDeniedException when using hasRole in WebSecurityConfigurerAdapter#configure

### ISSUE THREAD

**Issue by longthanhtran** [ulisesbocchio/spring-boot-security-saml#45]
When I use 

```
http
     .antMatchers("/admin/**")
     .hasRole("ADMIN")
```

inside WebSecurityConfigurerAdapter#configure() to prepare SwitchUserFilter#setSwitchUserUrl()

```
@Bean
public SwitchUserFilter switchUserFilter() {
    SwitchUserFilter filter = new SwitchUserFilter();
    filter.setUserDetailsService(customUserDetailsService);
    filter.setUsernameParameter("username");
    filter.setSwitchUserUrl("/admin/login_as");
    filter.setTargetUrl("/");
    return filter;
}
```

then I always got access denied with following log

> AuditEvent [timestamp=Thu Feb 22 10:35:42 ICT 2018, principal=_6ce0649c21a30ff021ab25b78ae57b8462f2b3bd75, type=AUTHORIZATION_FAILURE, data={details=com.github.ulisesbocchio.spring.boot.security.saml.user.SAMLUserDetails@9875dcb, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]

So I think I miss to implement SAMLUserDetails and want to know how the http...hasRole() uses SAMLUserDetails. For now I am trying to read the [sample](https://github.com/ulisesbocchio/spring-boot-security-saml-samples/tree/master/spring-security-saml-sample) but still unsure how to implement that.

Could you please see and guide me ? Many thanks.

**Comment by ulisesbocchio** [comment]
you'd have to implement your own `SAMLUserDetailsService`. There's a [section of the readme](https://github.com/ulisesbocchio/spring-boot-security-saml#add-your-own-samluserdetailsservice) that shows how to add your own.
For inspiration, you can look at the vanilla implementations of `SAMLUserDetailsServiceImpl` and `SAMLUserDetails` that come with this plugin.

**Comment by longthanhtran** [comment]
Yes, this time I follow to implement `SAMLUserDetailsService` as bean but the debug attempt fails to show loadUserBySAML being loaded. Hence I still frustrate don't sure how the bean being called. Can you please guide me a little further? Thanks.
