### ISSUE TITLE
 "Authentication statement is too old to be used with value" error for expired saml token

### ISSUE THREAD

**Issue by venkatpathy** [ulisesbocchio/spring-boot-security-saml#50]
I have another problem here, when i try accessing the resources after a day i get the below exception.

org.springframework.security.authentication.CredentialsExpiredException: Authentication statement is too old to be used with value 2018-03-27T10:12:45.301Z

below is the AuthnStatement,

urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
I would expect a user to login again in case of any exceptions in the older saml response when recieved

Any suggestions to handle this?

Thanks

**Comment by antonevane** [comment]
See the parent library issue:
https://github.com/spring-projects/spring-security-saml/issues/207

**Comment by venkatpathy** [comment]
Could you please elaborate on how it can be done if i am using just the spring boot properties to control the saml sso workflow? Thanks

**Comment by ulisesbocchio** [comment]
This are all the properties picked up by the plugin: https://github.com/ulisesbocchio/spring-boot-security-saml/blob/master/docs/properties/config-properties.md

If the property you need isn't there, you gonna need to add some code. Alternatively, submit a PR with the code to support the properties you need.

**Comment by ulisesbocchio** [comment]
I don't see how you could get that error using the default `SAMLUserDetails`, did you implement your own @venkatpathy ?

**Comment by venkatpathy** [comment]
@ulisesbocchio no i did not implement my own code.. i was able to resolve that issue with "saml.sso.profile-options.force-authn=true"

**Comment by ulisesbocchio** [comment]
alright, I'll close this then, thanks
