### ISSUE TITLE
Context path root doesn't start SSO login

### ISSUE THREAD

**Issue by synertech** [ulisesbocchio/spring-boot-security-saml#53]
For a some reason when I go to my context root page (e.g. http://localhost:8080) Spring Security doesn't redirect to SSO login page, but if I put anything after that (e.g. http://localhost:8080/anything) the authentication process start. How to solve this situation?

**Comment by ulisesbocchio** [comment]
Most likely / is not protected. You would have to add / to the protected urls through the security configurer

**Comment by ulisesbocchio** [comment]
this is caused by default property value:
```properties
saml.sso.logout.default-target-url = /
```
you can change it either by property or dsl:
```java
serviceProvider
  .logout()
  .defaultTargetURL("/")
```
This property specifies where you land after a successful logout. The plugin automatically assumes you need that path open because you need to land there while you're not logged in.
