### ISSUE TITLE
Change the AssertionConsumerServiceUrl (call back url after authentication) to point to different domain?

### ISSUE THREAD

**Issue by venkatpathy** [ulisesbocchio/spring-boot-security-saml#55]
Hi there

Is is possible to change the assertion consumer service url in the saml request to something other than the requesting service provider url? I know there is a spring boot property you provide to set the relative url which is "/saml/SSO". Currently it is "http://localhost:8080/saml/SSO". But i now need to redirect this to another base url that is something other than localhost (say http//xyz.domain.com) listening to the saml response from an IDP (which is azure ad in this case)? Is it most importantly a good practice doing this?

Thanks

**Comment by ulisesbocchio** [comment]
If I understand correctly, you want to redirect the actual SAML assertion to a different service? The entire purpose of spring-security-saml is to provide you the ability to consume and validate this SAML assertion, so in that case it probably wouldn't be a good practice and should incorporate all your SAML functionality in that other service. You can have your actual app just check for authentication, and if not authenticated (by session or token), redirect to the other service, let it handle all the authentication, and then make it redirect back to your app.

**Comment by ulisesbocchio** [comment]
closing due to no response
