### ISSUE TITLE
how to i add unprotected resources tried overriding configure httpSecurity but doesn work 

### ISSUE THREAD

**Issue by samtheprogrammer** [ulisesbocchio/spring-boot-security-saml#6]

**Comment by ulisesbocchio** [comment]
checked this real quick and you're right, I fixed the issue and will be released in 1.4 later today. 
I also updated the [Okta](https://github.com/ulisesbocchio/spring-boot-security-saml-samples/tree/master/spring-boot-security-saml-demo-okta) demo with sample configuration for unprotected resources.

**Comment by ulisesbocchio** [comment]
1.4 is in central already, enjoy

**Comment by samtheprogrammer** [comment]
Thanks a lot this really helped :+1:  :100:
