### ISSUE TITLE
security.SAMLProtocolMessageXMLSignatureSecurityPolicyRule 100 - SAML protocol message was not signed, skipping XML signature processing

### ISSUE THREAD

**Issue by thaniyarasu** [ulisesbocchio/spring-boot-security-saml#64]
we are getting this error messages, 
security.SAMLProtocolMessageXMLSignatureSecurityPolicyRule 100 - SAML protocol message was not signed, skipping XML signature processing.

our app server are running behind a ELB in a private subnet, our ssl termination is happening at ELB level. hence the request will reach to our spring-boot-app server with plain http after terminating from ELB.

How can we skip this error messages ?
can we disable this siginging SAML protocol message??

**Comment by ulisesbocchio** [comment]
This has nothing to do with HTTPS, it's telling you the SAML message is not signed. Checkout the `-signed` ended porperties here: https://github.com/ulisesbocchio/spring-boot-security-saml/blob/master/docs/properties/config-properties.md

You can specify them either through yaml/properties file or using the DSL
