### ISSUE TITLE
How to integrate into Spring MVC Java web app that is not maven or springboot

### ISSUE THREAD

**Issue by BillGoobs** [ulisesbocchio/spring-boot-security-saml#66]
I'm working on implementing SAML into an existing Java Spring MVC App that is NOT using maven or springboot.

Is this possible using this springboot/maven library?

How would we hook up and receive the callback from https://www.goobs.com/theapp/saml/SSO?SAMLResponse=jkghdkgdhjhdfgjdfjk

**Comment by ulisesbocchio** [comment]
Definitely possible. You’d have to download spring-security-saml and all its dependencies and put that in your application’s classpath. 
In terms of configuration you’d have to go with spring-security-saml, checkout their documentation which presents its config as XML. For javaconfig there’s an example in the examples repo of this plugin and although it’s for spring boot, the configuration it’s pretty generic. Checkout the readme

**Comment by BillGoobs** [comment]
Would we download and compile https://github.com/spring-projects/spring-security-saml?
Reference that jar in our project, along with all the other jars that spring-security-saml references?
All the http endpoints to send the SAMLRequest and receive back the SAMLResponse can be setup in our config files?  I'll take a look at this library and ask more questions.

**Comment by ulisesbocchio** [comment]
You can download the JAR files from any maven repo. You need to download spring-security-saml and all its dependencies, as well as any dependencies of the dependencies, and the dependencies of the dependencies of the dependencies and so on.... until you're done. I highly recommend using maven. You can setup a maven project and use this to get all the jars: https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html
But this is as far as I'll go though, we already went outside of the scope of this plugin. This kind of questions are better asked at https://stackoverflow.com/
