### ISSUE TITLE
Override SamlUserDetails

### ISSUE THREAD

**Issue by samtheprogrammer** [ulisesbocchio/spring-boot-security-saml#7]
Hi, 
Is there a way to override SAMLUserDetails so i can add custom extra attributes ?

**Comment by ulisesbocchio** [comment]
You'd have to provide your own SAMLUserDetailsService

**Comment by ulisesbocchio** [comment]
you can use:

```java
serviceProvider.
    .authenticationProvider()
    .userDetailsService(mySamlUserDetailsService());
```

in your `ServiceProviderConfigurer`

**Comment by samtheprogrammer** [comment]
Where we should write this code and fron where will we get service provider
object

On Aug 9, 2016 4:35 PM, "Ulises Bocchio" <notifications@github.com> wrote:

you can use:

serviceProvider.
    .authenticationProvider()
    .userDetailsService(mySamlUserDetailsService());

in your ServiceProviderConfigurer

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ulisesbocchio/spring-boot-security-saml/issues/7#issuecomment-238724699>,
or mute the thread

**Comment by samtheprogrammer** [comment]
Also I want to keep ur code as is and just override it in our code

**Comment by ulisesbocchio** [comment]
Look at the readme file in the DSL section it's explained how to customize the plugin. Also, you can look at the samples repository
