### ISSUE TITLE
Do you have any samples for SP initiated  SAML sso ?

### ISSUE THREAD

**Issue by jofisiva** [ulisesbocchio/spring-boot-security-saml#70]
The SP initiated is a spring application and it calls the WS02 for SAML request.  ws02 will route to ADFS for single sign-on authentication.

Do you have any sample for this kind of approach

**Comment by ulisesbocchio** [comment]
I don't have any example unfortunately. But if WS02 redirects to ADFS it should go back to WS02 transparently to your SP, so it should technically work as any other SAML integration
