### ISSUE TITLE
Not able to disable proxy-count tag in SAML AuthNRequest

### ISSUE THREAD

**Issue by sharma-sudhakar** [ulisesbocchio/spring-boot-security-saml#73]
If not mentioned property `saml.sso.profile-options.proxy-count` in my properties file, then my AuthNRequest having `<saml2p:Scoping ProxyCount="2" />` which is the default, If mentioned in the properties file as `saml.sso.profile-options.proxy-count=0` then in the AuthNRequest `<saml2p:Scoping ProxyCount="0" />`. How to eliminate this tag from SAML Request?

**Comment by ulisesbocchio** [comment]
I'm not sure I follow. can you elaborate?

**Comment by sharma-sudhakar** [comment]
Thanks, `saml.sso.profile-options.include-scoping` worked for me as expected.
