### ISSUE TITLE
Empty spring.factories

### ISSUE THREAD

**Issue by thiagolocatelli** [ulisesbocchio/spring-boot-security-saml#8]
Not actually an issue, but I am investigating on how to create my custom spring boot starter and I came across your repo. My question is: why is spring.factories file empty?

My understanding is that if the file is empty, the user has to manually include @EnableSAMLSSO, otherwise if the user includes the configurer class in the file, spring boot will automatically process the configuration without @EnableSAMLSSO. Is this correct?

**Comment by ulisesbocchio** [comment]
you're right, spring.factories in this library is not doing anything. Originally I was gonna make it a starter jar but then I modeled it based on other security plugins such as Spring OAuth2 that use annotations such as `EnableAuthorizationServer` and `EnableResourceServer`. For a sample where `spring.factories` is actually used you can check this other repo I have [jasypt-spring-boot](/ulisesbocchio/jasypt-spring-boot) where the module `jasypt-spring-boot-starter` all it does is to have a `spring.factories` to load the auto configuration
