### ISSUE TITLE
Unable to configure multi tenant metadata url for single IDP

### ISSUE THREAD

**Issue by sarjerav** [ulisesbocchio/spring-boot-security-saml#82]
Hi 
I want to make my application multi-tenant by using configuring multiple metadata url's at runtime.
I have single IDP but I want to configure multiple metadata urls at runtime.

So how can we achieve that using Spring Boot & SAML authentication?
Please update me ASAP on this as I have never seen this before.

**Comment by devsteppe9** [comment]
Hello @sarjerav 
Did you solved your problem? I am struggling same problem. We developing system with Azure AD, our customers needs to configure their own Azure account IdP MetaData on the go.
If you have any suggestions please help me!
