### ISSUE TITLE
Custom Global Logout

### ISSUE THREAD

**Issue by JuMp3** [ulisesbocchio/spring-boot-security-saml#94]
I need to configure a custom GlobalHanlder; I would like to understand how to do it correctly.

I noticed that the LogoutConfigurer allows you to define globalHandler and localHandler but in reality if I use it the custom logout handler does not happen correctly. Where am I doing wrong?

this is my configuration in my class that extends ServiceProviderConfigurerAdapter:
`...  .and() .logout()
                    .globalHandler(customGlobalLogoutHandler())
                    .localHandler(customLocalLogoutHandler())
                    .successHandler(logoutSuccessHandler())
                    .clearAuthentication(true)
                    .invalidateSession(true);`

And this is my CustomGlobalLogoutHandler:

    public class CustomGlobalLogoutHandler implements LogoutHandler {

      private final ILogoutService logoutService;
  
      public CustomGlobalLogoutHandler(ILogoutService logoutService) {
          this.logoutService = logoutService;
      }
  
      @Override
      public void logout(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, Authentication authentication) {
          if (authentication != null && authentication.getPrincipal() instanceof UserInfo) {
              log.info("**** START -> GlobalLogout {} ****", authentication.getName());
              UserInfo userInfo = (UserInfo) authentication.getPrincipal();
              logoutService.logout(userInfo.getUsername());
              log.info("****  END  -> GlobalLogout {} ****", authentication.getName());
          }
      }
    }

My custom business logic works (logoutService.logout), but in reality there is no logout on the IdP.
If i remove the globalHandler and localHandler the logout on the Idp works.
Can you help me? Many thanks in advance!

**Comment by JuMp3** [comment]
For now I solved it, as workaround, adding the logout logic of the SecurityContextLogoutHandler and CookieClearingLogoutHandler classes:

    @Override
    public void logout(HttpServletRequest request, HttpServletResponse response, Authentication authentication) {

        // custom business logic
        if (authentication != null && authentication.getPrincipal() instanceof UserInfo) {
            log.info("**** START -> GlobalLogout {} ****", authentication.getName());
            UserInfo userInfo = (UserInfo) authentication.getPrincipal();
            logoutService.logout(userInfo.getUsername());
            log.info("****  END  -> GlobalLogout {} ****", authentication.getName());
        }

        // invalidHttpSession
        HttpSession session = request.getSession(false);
        if (session != null) {
            session.invalidate();
            if (log.isDebugEnabled()) {
                log.debug(String.format("Invalidated session %s", session.getId()));
            }
        }

        // clearAuthentication
        SecurityContext context = SecurityContextHolder.getContext();
        context.setAuthentication(null);
        SecurityContextHolder.clearContext();

        // delete cookie
        List<Function<HttpServletRequest, Cookie>> cookieList = new ArrayList();
        cookieList.add((httpRequest) -> {
            Cookie cookie = new Cookie("JSESSIONID", null);
            String cookiePath = httpRequest.getContextPath() + "/";
            cookie.setPath(cookiePath);
            cookie.setMaxAge(0);
            cookie.setSecure(httpRequest.isSecure());
            return cookie;
        });

        cookieList.forEach((f) -> response.addCookie(f.apply(request)));
    }


but I guess it's not the "cleanest" solution

**Comment by ulisesbocchio** [comment]
when you override the LogoutHandler you're overriding the default functionality. Take a look at how the logout handler is initialized https://github.com/ulisesbocchio/spring-boot-security-saml/blob/master/spring-boot-security-saml/src/main/java/com/github/ulisesbocchio/spring/boot/security/saml/configurer/builder/LogoutConfigurer.java
```java
if (globalHandler == null) {
            SecurityContextLogoutHandler logoutHandler = createDefaultGlobalHandler();
            logoutHandler.setInvalidateHttpSession(Optional.ofNullable(invalidateSession).orElseGet(config::isInvalidateSession));
            logoutHandler.setClearAuthentication(Optional.ofNullable(clearAuthentication).orElseGet(config::isClearAuthentication));
            globalHandler = postProcess(logoutHandler);
        }
```
The default one is a `SecurityContextLogoutHandler` so if you want it to carry the same functionality, just extend it, and call `super.logout(request, response)` before or after your code, depending on when you want your code to run

**Comment by JuMp3** [comment]
> `SecurityContextLogoutHandler`

Ok, perfect! In fact, it's the best solution. I followed your advice: I will extend my CustomGlobalLogoutHandler class with SecurityContextLogoutHandler and leave my custom logic  + logic for the cookie.
Thank you so much for your availability and timing!

Now my class will be:

    public class CustomGlobalLogoutHandler extends SecurityContextLogoutHandler implements LogoutHandler {

      private final ILogoutService logoutService;
  
      public CustomGlobalLogoutHandler(ILogoutService logoutService) {
          this.logoutService = logoutService;
      }
  
      @Override
      public void logout(HttpServletRequest request, HttpServletResponse response, Authentication authentication) {
  
          // custom business logic
          if (authentication != null && authentication.getPrincipal() instanceof UserInfo) {
              log.info("**** START -> GlobalLogout {} ****", authentication.getName());
              UserInfo userInfo = (UserInfo) authentication.getPrincipal();
              logoutService.logout(userInfo.getUsername());
              log.info("****  END  -> GlobalLogout {} ****", authentication.getName());
          }
  
          // delete cookie
          List<Function<HttpServletRequest, Cookie>> cookieList = new ArrayList();
          cookieList.add((httpRequest) -> {
              Cookie cookie = new Cookie("JSESSIONID", null);
              String cookiePath = httpRequest.getContextPath() + "/";
              cookie.setPath(cookiePath);
              cookie.setMaxAge(0);
              cookie.setSecure(httpRequest.isSecure());
              return cookie;
          });
  
          cookieList.forEach((f) -> response.addCookie(f.apply(request)));
  
          super.logout(request, response, authentication);
      }
    }

**Comment by ulisesbocchio** [comment]
Excellent! you're very welcome. On second inspection tough, I realized the `SAMLLogoutFilter` is initialized as such:
```java
SAMLLogoutFilter samlLogoutFilter = new SAMLLogoutFilter(successHandler, new LogoutHandler[]{localHandler}, new LogoutHandler[]{globalHandler});
```
So technically you can chain multiple logout handlers to the SAMLLogoutFilter. Now, I didn't foresee that you may wanna provide multiple handlers on the DSL and only allow for one, that's my bad, so I'll try to add the functionality at some point. That will allow you to use your original, non-extended handler.
If you'd still wanna follow a similar pattern today, you could do:
```java
class DelegateCompositeLogoutHandler implements LogoutHandler {
    private LogoutHandler[] handlers;
     
    public DelegateCompositeLogoutHandler(LogoutHandler[] handlers) {
        this.handlers = handlers;
    }
     
    @Override
    public void logout(HttpServletRequest request, HttpServletResponse response, Authentication authentication) {
        for(LogoutHandler handler: this.handlers) {
             handler.logout(request, response, authentication);
        }
    }
}
```
and then initialize it like:
```java
@Configuration
public static class MyServiceProviderConfig extends ServiceProviderConfigurerAdapter {

    @Bean
    public LogoutHandler customLogoutHandler() {
         return new DelegateCompositeLogoutHandler(LogoutHandler[]{new SecurityContextLogoutHandler(), new CustomGlobalLogoutHandler()});
    }

    @Override
    public void configure(ServiceProviderBuilder serviceProvider) throws Exception {
        // @formatter:off
        serviceProvider 
            .logout()
                .globalHandler(customLogoutHandler()) 
                .localHandler(customLogoutHandler())
        // @formatter:on
    }
}
```
